
id: forms.clinfhir.com
#id: hl7.fhir.nz.base
canonical: http://forms.clinfhir.com
version: 1.1.0
name: Resources for Forms
title: Resources for Forms
status: active
publisher:
  name: David Hay
  email: mailto:david.hay25@gmail.com
description: Resources for Forms
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2021+
# releaseLabel: Release
releaseLabel: CI Build

menu:
  IG Home: index.html

